on:
  push:

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - run: go build -o reader_linux_amd64 .
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o reader_windows_amd64.exe .
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o reader_darwin_amd64 .
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o reader_darwin_arm64 .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            reader_linux_amd64
            reader_windows_amd64.exe
            reader_darwin_amd64
            reader_darwin_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}